# Generated by Django 4.2.4 on 2023-11-23 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_authgroup_authgrouppermissions_authpermission_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.AlterModelTable(
            name='djangomigrations',
            table='users',
        ),
    ]
