# Generated by Django 4.2.4 on 2023-12-26 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_delete_stock_alter_djangomigrations_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
